spring:
	datasource:
    	url: jdbc:mysql://localhost:3306/test
    	password: root
    	username: root
    	driver-class-name: com.mysql.jdbc.Driver
	jpa:
		database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
		hibernate:
			ddl-auto: update
      
server:
	port:2019